---
# tasks file for db
- name: change mongod config file
  template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
  notify: restart mongod

- name: show environment
  debug:
    msg: "this is {{ env }} environment"