all:
  children:
    app:
      hosts:
        appserver:
          ansible_host: 35.241.242.123 # ansible_user=appuser ansible_private_key_file=~/.ssh/appuser
    db:
      hosts:
        dbserver:
          ansible_host: 146.148.10.90 # ansible_user=appuser ansible_private_key_file=~/.ssh/appuser

