---
# tasks file for app
- name: Add unit file for Puma
  copy:
    src: files/puma.service
    dest: /etc/systemd/system/puma.service
  notify: restart puma

- name: Add config for DB connection
  template:
    src: templates/db_config.j2
    dest: /home/appuser/db_config
    owner: appuser
    group: appuser

- name: enable puma
  systemd: name=puma enabled=yes daemon_reload=yes

- name: show environment
  debug:
    msg: "this is {{ env }} environment"