---
- name: Configure App
  hosts: app
  become: true

  vars:
   db_host: 10.132.15.200

  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: restart puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config
        owner: appuser
        group: appuser

    - name: enable puma
      systemd: name=puma enabled=yes daemon_reload=yes

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted daemon_reload=yes
