all:
  children:
    app:
      hosts:
        appserver:
          ansible_host: 35.187.105.76 # ansible_user=appuser ansible_private_key_file=~/.ssh/appuser
    db:
      hosts:
        dbserver:
          ansible_host: 34.76.22.20   # ansible_user=appuser ansible_private_key_file=~/.ssh/appuser

